stages:
  - build

build-rust-latest:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_IMAGE: grauwoelfchen/rust
  services:
    - docker:dind
  before_script:
    - docker version
    - echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USERNAME
      --password-stdin $REGISTRY_HOSTNAME
  script:
    - cd rust
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:latest latest
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:latest
      $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:latest
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:latest
  only:
    - release

build-rust-nightly:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_IMAGE: grauwoelfchen/rust
  services:
    - docker:dind
  before_script:
    - docker version
    - echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USERNAME
      --password-stdin $REGISTRY_HOSTNAME
  script:
    - cd rust
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:nightly nightly
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:nightly
      $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:nightly
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_IMAGE:nightly
  only:
    - release
