stages:
  - build
  - deploy

# TODO
# * remove make
# * share artifacts between stages
# * use gitlab image registry

.docker_login:
  - &docker_login
    echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USERNAME
    --password-stdin $REGISTRY_HOSTNAME

.build_gentoo: &build_gentoo
  - cd gentoo
  - export TAG=$(date +%Y%m%d)
  - make build:${TARGET}:${TAG}
  - docker tag $REGISTRY_HOSTNAME/grauwoelfchen/gentoo-${TARGET}:$TAG
    $REGISTRY_HOSTNAME/grauwoelfchen/gentoo-${TARGET}:$TAG

.install_make: &install_make
  - apk add --no-cache make

build-gentoo-amd64:
  stage: build
  image: docker:latest
  variables:
    TARGET: amd64
  services:
    - docker:dind
  before_script:
    - *install_make
  script:
    - *build_gentoo
  only:
    - master

build-gentoo-amd64-nomultilib:
  stage: build
  image: docker:latest
  variables:
    TARGET: amd64-nomultilib
  services:
    - docker:dind
  before_script:
    - *install_make
  script:
    - *build_gentoo
  only:
    - master

deploy-gentoo-amd64:
  stage: deploy
  image: docker:latest
  variables:
    TARGET: amd64
  services:
    - docker:dind
  before_script:
    - *install_make
    - docker version
    - *docker_login
  script:
    - *build_gentoo
    - docker push $REGISTRY_HOSTNAME/grauwoelfchen/gentoo-${TARGET}:$TAG
  after_script:
    - docker logout
  only:
    - /^gentoo-amd64-.*/
  except:
    - branches
    - /^gentoo-amd64-nomultilib-.*/

deploy-gentoo-amd64-nomultilib:
  stage: deploy
  image: docker:latest
  variables:
    TARGET: amd64-nomultilib
  services:
    - docker:dind
  before_script:
    - *install_make
    - docker version
    - *docker_login
  script:
    - *build_gentoo
    - docker push $REGISTRY_HOSTNAME/grauwoelfchen/gentoo-${TARGET}:$TAG
  after_script:
    - docker logout
  only:
    - /^gentoo-amd64-nomultilib-.*/
  except:
    - branches

build-rust-stable:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_NAME: grauwoelfchen/rust
    CONTAINER_TAG: stable
  services:
    - docker:dind
  script:
    - cd rust
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      stable
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
  after_script:
    - docker logout
  only:
    - rust-stable

build-rust-stable-fearless:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_NAME: grauwoelfchen/rust
    CONTAINER_TAG: stable-fearless
  services:
    - docker:dind
  script:
    - cd rust
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      stable-fearless
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
  after_script:
    - docker logout
  only:
    - rust-stable-fearless

build-rust-nightly:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_NAME: grauwoelfchen/rust
    CONTAINER_TAG: nightly
  services:
    - docker:dind
  script:
    - cd rust
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      nightly
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
  after_script:
    - docker logout
  only:
    - rust-nightly

build-rust-nightly-fearless:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_NAME: grauwoelfchen/rust
    CONTAINER_TAG: nightly-fearless
  services:
    - docker:dind
  script:
    - cd rust
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      nightly-fearless
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
  after_script:
    - docker logout
  only:
    - rust-nightly-fearless

build-rust-vet-tools-stable:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_NAME: grauwoelfchen/rust-vet-tools
    CONTAINER_TAG: stable
  services:
    - docker:dind
  script:
    - cd rust-vet-tools
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      stable
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
  after_script:
    - docker logout
  only:
    - rust-vet-tools-stable

build-rust-vet-tools-nightly:
  stage: build
  image: docker:latest
  variables:
    CONTAINER_NAME: grauwoelfchen/rust-vet-tools
    CONTAINER_TAG: nightly
  services:
    - docker:dind
  script:
    - cd rust-vet-tools
    - docker build -t $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      nightly
    - docker tag $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
      $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
    - docker push $REGISTRY_HOSTNAME/$CONTAINER_NAME:$CONTAINER_TAG
  after_script:
    - docker logout
  only:
    - rust-vet-tools-nightly
